"""initial schema

Revision ID: 7ba49989aaaf
Revises: 
Create Date: 2026-07-26 05:29:29.519163
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ba49989aaaf'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_drift_alerts_agent_name'), 'drift_alerts', ['agent_name'], unique=False
    )
    op.create_table('drift_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('built_at', sa.DateTime(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('avg_response_length', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('avg_token_count', sa.Float(), nullable=True),
    sa.Column('embedding_centroid', sqlite.JSON(), nullable=True),
    sa.Column('response_length_distribution', sqlite.JSON(), nullable=True),
    sa.Column('tool_call_distribution', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_drift_baselines_agent_name'), 'drift_baselines', ['agent_name'], unique=False
    )
    op.create_table('drift_rebuild_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_drift_rebuild_requests_agent_name'),
        'drift_rebuild_requests',
        ['agent_name'],
        unique=False,
    )
    op.create_table('traces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('parent_span_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('input_data', sqlite.JSON(), nullable=True),
    sa.Column('output_data', sqlite.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spans_agent_name'), 'spans', ['agent_name'], unique=False)
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_agent_name'), table_name='spans')
    op.drop_table('spans')
    op.drop_table('traces')
    op.drop_index(op.f('ix_drift_rebuild_requests_agent_name'), table_name='drift_rebuild_requests')
    op.drop_table('drift_rebuild_requests')
    op.drop_index(op.f('ix_drift_baselines_agent_name'), table_name='drift_baselines')
    op.drop_table('drift_baselines')
    op.drop_index(op.f('ix_drift_alerts_agent_name'), table_name='drift_alerts')
    op.drop_table('drift_alerts')
    # ### end Alembic commands ###
